package Controller;

import java.io.IOException;
//import java.util.Optional;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.Node;
//import javafx.scene.control.Alert;
import javafx.scene.control.Button;
//import javafx.scene.control.ButtonType;
import javafx.stage.Stage;
//import javafx.scene.control.Alert.AlertType;

public class AuthentificationClientController {
	@FXML
	private Button bConnecter;

	@FXML
	private Button bInscrir;
	// Event Listener on Button[#bConnecter].onAction
	@FXML
	public void actionConnecter(ActionEvent event) { 
		// TODO Autogenerated
			Parent root;
			try {
				root = FXMLLoader.load(getClass().getResource("/View/Connexion.fxml"));

		    Scene scene = new Scene(root);
		    Stage stage  = (Stage) ((Node) event.getSource()).getScene().getWindow();
		    stage.setTitle("Connexion");
		    stage.setScene(scene);
		    stage.show();
		    
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		
	}
	
	// Event Listener on Button[#bInscrir].onAction
		@FXML
		public void actionInscrire(ActionEvent event) { 
			// TODO Autogenerated
			Parent root;
			try {
				root = FXMLLoader.load(getClass().getResource("/View/SinsecrirClient.fxml"));
		

		    Scene scene = new Scene(root);
		    Stage stage  = (Stage) ((Node) event.getSource()).getScene().getWindow();
		    stage.setTitle("Connexion");
		    stage.setScene(scene);
		    stage.show();
		    
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		
	}
}
