package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class ContacteController {
	@FXML
	private Button bRetour;

	// Event Listener on Button[#bRetour].onAction
	@FXML
	public void actionRetour(ActionEvent event) {
		// TODO Autogenerated
		
		try {
			Parent root= FXMLLoader.load(getClass().getResource("/View/Accueil.fxml"));
		

		    Scene scene = new Scene(root);
		    Stage stage  = (Stage) ((Node) event.getSource()).getScene().getWindow();
		    stage.setTitle("Votre profil");
		    stage.setScene(scene);
		    stage.show();
		    
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
}
